### ISSUE TITLE
Replace "https://" with "git://"

### ISSUE THREAD

**Issue by Affixes** [Yive/RotateSRV#1]
Upon cloning, some systems may experience issues downloading the repository using HTTPS. I would suggest updating the `SETUP.md` to say `git clone git://github.com/Yive/RotateSRV`.

```
root@vps2-atl:/opt/rotatesrv# git clone https://github.com/Yive/RotateSRV
Cloning into 'RotateSRV'...
fatal: Unable to find remote helper for 'https'
```

**Comment by Yive** [comment]
Sorry for the late reply. Most of the time when I've had to clone something, https works instead of the git protocol. I'm going to keep it as https because you're the only person who has brought this up. I will add a note in the setup guide for those who get that error though.
